language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.2
    - android-24
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - addon-google_apis-google-22
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-8933bad161af4178b1185d1a37fbf41ea5269c55
    - android-sdk-license-.+
    - google-gdk-license-.+
  script:
    - ./gradlew build
  cache:
    directories:
    - $HOME/.m2
    - $HOME/.gradle